CREATE TABLE `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PATIENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `AGE` TINYINT(1) NOT NULL,
  `GENDER` ENUM('MALE', 'FEMALE', 'OTHERS'),
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `PRESCRIPTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DIAGNOSIS` TEXT DEFAULT NULL,
  `MEDICINES` TEXT DEFAULT NULL,
  `NEXT_VISIT_DATE` DATETIME DEFAULT NULL,
  `CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `USER_ID` bigint(20) NOT NULL,
  `PATIENT_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT FK_USER_ID FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`ID`),
  CONSTRAINT FK_PATIENT_ID FOREIGN KEY (`PATIENT_ID`) REFERENCES `PATIENT`(`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;