
INSERT INTO `USER`(`ID`, `USERNAME`, `PASSWORD`) VALUES (10, 'doctor', '$2y$12$/HVZq.cgdpdEhAJwkREMlurYJ3rILhZkaH57h72GSecGUi3sVAa0.');


INSERT INTO `PATIENT`(`ID`, `NAME`, `AGE`, `GENDER`) VALUES (1, 'patient 1', 30, 'MALE');
INSERT INTO `PATIENT`(`ID`, `NAME`, `AGE`, `GENDER`) VALUES (2, 'patient 2', 35, 'FEMALE');
INSERT INTO `PATIENT`(`ID`, `NAME`, `AGE`, `GENDER`) VALUES (3, 'patient 3', 30, 'MALE');


INSERT INTO `PRESCRIPTION`(`ID`, `DIAGNOSIS`, `MEDICINES`, `NEXT_VISIT_DATE`, `CREATED_AT`, `CREATED_BY`, `PATIENT_ID`)
VALUES (NULL, 'Normal Fever', 'Nape extra', '2020-06-18 13:17:17', NOW(), 10, 1);
INSERT INTO `PRESCRIPTION`(`ID`, `DIAGNOSIS`, `MEDICINES`, `NEXT_VISIT_DATE`, `CREATED_AT`, `CREATED_BY`, `PATIENT_ID`)
VALUES (NULL, 'Normal Fever', 'Nape extra', '2020-06-18 13:17:17', NOW(), 10, 2);